### ISSUE TITLE
You are not logged in.

### ISSUE THREAD

**Issue by AstroCB** [giantswarm/swarm-ogar#1]
I've installed all of the dependencies successfully and cloned the repo, but when I run `make docker-run` in the directory, I get the following:

```
%!(EXTRA *errgo.Err=You are not logged in.)%!(EXTRA *errgo.Err=You are not logged in.)%!(EXTRA *errgo.Err=You are not logged in.)docker build -t registry.giantswarm.io//ogar .
FATA[0000] Invalid namespace name (). Cannot be fewer than 2 or more than 255 characters. 
make: *** [docker-build] Error 1
```

What exactly am I not logged into and how can I log in?

**Comment by zeisss** [comment]
Hello AstroCB,

sorry for the delay. You have to login to the registry with your docker client separately. Just do the following:

```
docker login https://registry.giantswarm.io
Username: <giantswarm username>
Email: <canbeempty>
Password: <password>
```

Afterwards you should be able to push. You can find more information here: https://docs.giantswarm.io/reference/registry/

**Comment by AstroCB** [comment]
That's what I thought; thanks!
