### ISSUE TITLE
Authentication is required. error

### ISSUE THREAD

**Issue by sayginburak** [giantswarm/swarm-ogar#2]
Hi,
I can start the server and play on my local machine and do ngrok. But when i tried to deploy to giantswarm at the end of the process it gives this error. how can I solve this?

.....
....
Successfully built f7b9049acfc6
docker push registry.giantswarm.io/sayginburak/ogar
The push refers to a repository [registry.giantswarm.io/sayginburak/ogar](len: 1)
Sending image list
FATA[0002] Authentication is required.
make: **\* [docker-push] Error 1

**Comment by zeisss** [comment]
Hello sayginburak,

sorry for the delay. You have to login to the registry with your docker client separately. Just do the following:

```
docker login https://registry.giantswarm.io
Username: <giantswarm username>
Email: <canbeempty>
Password: <password>
```

Afterwards you should be able to push. You can find more information here: https://docs.giantswarm.io/reference/registry/

**Comment by kordless** [comment]
@sayginburak double checking that you have a Giant Swarm account, correct? If not, I can address that for you.

**Comment by sayginburak** [comment]
Yes, I have a Giant Swarm account. I have already logged in to swarm. I did it again, but same error. Full output is here, I think this is not a login problem. 

docker build -t registry.giantswarm.io/sayginburak/ogar .
Sending build context to Docker daemon 563.2 kB
Sending build context to Docker daemon
Step 0 : FROM google/nodejs
 ---> d579dbe02fb7
Step 1 : WORKDIR /Ogar
 ---> Using cache
 ---> c5acb67bbee2
Step 2 : RUN apt-get install git -y
 ---> Using cache
 ---> cd18a320a8ac
Step 3 : RUN git clone git://github.com/sayginburak/Ogar4.git Ogar
 ---> Using cache
 ---> bfe156707ac0
Step 4 : RUN npm install ./Ogar
 ---> Using cache
 ---> d828f213f5fc
Step 5 : RUN npm install ws
 ---> Using cache
 ---> d91ea5535a68
Step 6 : EXPOSE 443
 ---> Using cache
 ---> f1d4981f176e
Step 7 : ENTRYPOINT /nodejs/bin/node Ogar/index.js --game 0
 ---> Using cache
 ---> 59c14dc57b2b
Successfully built 59c14dc57b2b
docker push registry.giantswarm.io/sayginburak/ogar
The push refers to a repository [registry.giantswarm.io/sayginburak/ogar](len: 1)
Sending image list
FATA[0004] Authentication is required.
make: **\* [docker-push] Error 1

**Comment by zeisss** [comment]
Hey,

random thought: Does your password have a questionmark? A colleague reported some problems with such a password and the registry, but I didn't have time to look into it yet.

Also, please check that the giantswarm registry is listed in your `~/.dockercfg`.
- Stephan

**Comment by sayginburak** [comment]
I have logged in with "swarm login" command. Now I tried the "docker login https://registry.giantswarm.io" and It worked. Thanks guys.

**Comment by kordless** [comment]
Great to hear! Hope you are back to eating dots.

**Comment by zeisss** [comment]
Thanks for the feedback. I have created an internal ticket to make the process here more smoothly. :cake:
